### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fhemberger**
Also get rid of insecure `semver` version

### CODE REVIEW

**Comment by mlochbaum** [comment]
Thanks; I've been meaning to do this for a while.

**Comment by fhemberger** [comment]
Can you please also push a new version to npm? Thanks!

**Comment by fhemberger** [comment]
> Can you please also push a new version to npm? Thanks!
*bump* /cc @mlochbaum

**Comment by mlochbaum** [comment]
Published; sorry for the wait. Not sure how I missed this the first go around...

**Pull request merged**
